A2ZOnlineStore/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A2ZOnlineStore.Data.Interfaces;
using A2ZOnlineStore.Data.Models;
using A2ZOnlineStore.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace A2ZOnlineStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository _ProductRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IBrandRepository _brandRepository;

        public ProductController(IProductRepository ProductRepository, ICategoryRepository categoryRepository, IBrandRepository brandRepository)
        {
            _ProductRepository = ProductRepository;
            _categoryRepository = categoryRepository;
            _brandRepository = brandRepository;
        }

        public ViewResult List(string category = null)
        {
            string _category = category;
            IEnumerable<Product> Products;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                Products = _ProductRepository.Products.OrderBy(p => p.ProductId);
                currentCategory = "All Products";
            }
            else
            {
                Products = _ProductRepository.Products.Where(p => p.Category.CategoryId.ToString() == category).OrderBy(p => p.Name);
                currentCategory = _category;
            }

            return View(new ProductsListViewModel
            {
                Products = Products,
                CurrentCategory = currentCategory
            });
        }

        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<Product> Products;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                Products = _ProductRepository.Products.OrderBy(p => p.ProductId);
            }
            else
            {
                Products = _ProductRepository.Products.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Product/List.cshtml", new ProductsListViewModel { Products = Products, CurrentCategory = "All Products" });
        }

        public ViewResult Details(int ProductId)
        {
            var Product = _ProductRepository.Products.FirstOrDefault(d => d.ProductId == ProductId);
            if (Product == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(Product);
        }

        public ViewResult AddProduct(int ProductId = 0)
        {
            ViewBag.Categories = _categoryRepository.Categories;
            ViewBag.brand = _brandRepository.Brands;
            Product model = new Product();
            if (ProductId == 0)
            {
                return View(model);
            }
            model = _ProductRepository.GetProductById(ProductId);
            if(model == null)
                return View(new Product());
            return View(model);
        }

        [HttpPost]
        public ActionResult AddProduct(Product product)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = _categoryRepository.Categories;
                ViewBag.brand = _brandRepository.Brands;
                return View(product);
            }
           _ProductRepository.AddProduct(product);

            return RedirectToAction(nameof(List));
        }


        public ViewResult AddBrand()
        {            
            return View(new Brand());
        }

        [HttpPost]
        public ActionResult AddBrand(Brand brand)
        {
            if (!ModelState.IsValid)
            {
                return View(brand);
            }
            _brandRepository.AddBrand(brand);
            return RedirectToAction(nameof(List));
        }

        public ViewResult AddCategory()
        {
            return View(new Category());
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            _categoryRepository.AddCategory(category);
            return RedirectToAction(nameof(List));
        }
    }
}

A2ZOnlineStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using A2ZOnlineStore.Data.Interfaces;
using A2ZOnlineStore.Data.Models;
using A2ZOnlineStore.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace A2ZOnlineStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _ProductRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IProductRepository ProductRepository, ShoppingCart shoppingCart)
        {
            _ProductRepository = ProductRepository;
            _shoppingCart = shoppingCart;
        }

        [Authorize]
        public ViewResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(shoppingCartViewModel);
        }

        [Authorize]
        public RedirectToActionResult AddToShoppingCart(int ProductId)
        {
            var selectedProduct = _ProductRepository.Products.FirstOrDefault(p => p.ProductId == ProductId);
            if (selectedProduct != null)
            {
                _shoppingCart.AddToCart(selectedProduct, 1);
            }
            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int ProductId)
        {
            var selectedProduct = _ProductRepository.Products.FirstOrDefault(p => p.ProductId == ProductId);
            if (selectedProduct != null)
            {
                _shoppingCart.RemoveFromCart(selectedProduct);
            }
            return RedirectToAction("Index");
        }

    }

}

A2ZOnlineStore/Views/Shared/Carousel.cshtml
<div class="row carousel-holder marginTop1" >
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" >
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel1.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel2.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel3.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

A2ZOnlineStore/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            @{ if (User.IsInRole("admin"))
                {                        
                    <li>
                        <a asp-controller="Admin"
                            asp-action="Index"
                            class="dropdown-toggle" data-toggle="dropdown">Administration<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a asp-controller="Product" asp-action="AddProduct">Add Product</a>
                            </li>
                            <li>
                                <a asp-controller="Product" asp-action="AddCategory">Add Catgeory</a>
                            </li>
                            <li>
                                <a asp-controller="Product" asp-action="AddBrand">Add Brand</a>
                            </li>                                
                        </ul>

                    </li>
                }
             }
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

A2ZOnlineStore/Views/Shared/ProductOverviewSummary.cshtml
@model Product   

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Product" asp-action="Details" asp-route-id="@Model.ProductId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-pieId="@Model.ProductId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

A2ZOnlineStore/Views/Shared/ProductsSummary.cshtml
@model Product

<div class="col-sm-4 col-lg-4 col-md-4" style="min-height:500px; max-height:500px;">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnailUrl" alt="" class="product-image" />
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-controller="Product" asp-action="Details" asp-route-ProductId="@Model.ProductId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="text-right addToCart">
            <p class="button ">
                <a class="btn btn-success" id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-ProductId="@Model.ProductId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

A2ZOnlineStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>A2Z Company</title>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">A2Z Online Store</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="dropdown">
                        <a asp-controller="Product"
                           asp-action="Index"
                           class="dropdown-toggle" data-toggle="dropdown">Products<b class="caret"></b></a>
                        @await Component.InvokeAsync("CategoryMenu")
                    </li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
                @await Html.PartialAsync("LoginPartial")
                <form class="navbar-form navbar-right" asp-controller="Product" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search for a Product" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content" style="padding:50px;">
        @RenderBody()
        <hr />
        <footer>
            <p><a target="_blank" href="https://github.com/alihoshaimy">&copy; 2019 - Ali Al Hoshaimy</a></p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>